language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
before_install:
  - "mkdir -p ~/.npm"
install:
  - npm install
  - npm install git://github.com/hybridgroup/cylon.git
  - npm install -g jshint istanbul codeclimate-test-reporter
script:
  - make ci
  - CODECLIMATE_REPO_TOKEN=6c4a26b64c162f34520b2fb2b866aafbd637a46b42ae558f24c044aeeaac2dd8 codeclimate-test-reporter < coverage/lcov.info
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
